apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  namespace: mtb-survey
spec:
  controller: k8s.io/ingress-nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-config
  namespace: mtb-survey
data:
  use-forwarded-headers: "true"
  proxy-body-size: "10m"
  client-max-body-size: "10m"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtb-survey-ingress
  namespace: mtb-survey
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: mtb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mtb-survey
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: flask-api
            port:
              number: 80 